// AUTO-GENERATED by scripts/gen-icons.mjs — run `npm run gen:icons` after adding icons.
import type { ForwardRefExoticComponent, SVGProps } from 'react'

import Activity from '~icons/lucide/activity'
import ArrowLeft from '~icons/lucide/arrow-left'
import ArrowRight from '~icons/lucide/arrow-right'
import ArrowUpRight from '~icons/lucide/arrow-up-right'
import BookOpen from '~icons/lucide/book-open'
import BookOpenCheck from '~icons/lucide/book-open-check'
import Bot from '~icons/lucide/bot'
import Check from '~icons/lucide/check'
import ChevronDown from '~icons/lucide/chevron-down'
import ChevronLeft from '~icons/lucide/chevron-left'
import ChevronRight from '~icons/lucide/chevron-right'
import ChevronUp from '~icons/lucide/chevron-up'
import CircleCheck from '~icons/lucide/circle-check'
import CircleQuestionMark from '~icons/lucide/circle-question-mark'
import CircuitBoard from '~icons/lucide/circuit-board'
import ClipboardCheck from '~icons/lucide/clipboard-check'
import ClipboardList from '~icons/lucide/clipboard-list'
import CloudUpload from '~icons/lucide/cloud-upload'
import Construction from '~icons/lucide/construction'
import Copy from '~icons/lucide/copy'
import Cpu from '~icons/lucide/cpu'
import Dices from '~icons/lucide/dices'
import Ellipsis from '~icons/lucide/ellipsis'
import Eye from '~icons/lucide/eye'
import EyeOff from '~icons/lucide/eye-off'
import FileText from '~icons/lucide/file-text'
import FingerprintPattern from '~icons/lucide/fingerprint-pattern'
import FlaskConical from '~icons/lucide/flask-conical'
import GraduationCap from '~icons/lucide/graduation-cap'
import HardDrive from '~icons/lucide/hard-drive'
import IdCard from '~icons/lucide/id-card'
import Info from '~icons/lucide/info'
import KeyRound from '~icons/lucide/key-round'
import Laptop from '~icons/lucide/laptop'
import LayoutDashboard from '~icons/lucide/layout-dashboard'
import Library from '~icons/lucide/library'
import ListChecks from '~icons/lucide/list-checks'
import Lock from '~icons/lucide/lock'
import LogIn from '~icons/lucide/log-in'
import LogOut from '~icons/lucide/log-out'
import MessageCircleQuestionMark from '~icons/lucide/message-circle-question-mark'
import Minus from '~icons/lucide/minus'
import MonitorPlay from '~icons/lucide/monitor-play'
import MonitorSmartphone from '~icons/lucide/monitor-smartphone'
import Moon from '~icons/lucide/moon'
import NotebookText from '~icons/lucide/notebook-text'
import PanelLeftClose from '~icons/lucide/panel-left-close'
import PanelLeftOpen from '~icons/lucide/panel-left-open'
import Pen from '~icons/lucide/pen'
import PenLine from '~icons/lucide/pen-line'
import Pencil from '~icons/lucide/pencil'
import Plus from '~icons/lucide/plus'
import RefreshCw from '~icons/lucide/refresh-cw'
import Rocket from '~icons/lucide/rocket'
import ScanSearch from '~icons/lucide/scan-search'
import School from '~icons/lucide/school'
import ScrollText from '~icons/lucide/scroll-text'
import Search from '~icons/lucide/search'
import SearchX from '~icons/lucide/search-x'
import Settings2 from '~icons/lucide/settings-2'
import ShieldCheck from '~icons/lucide/shield-check'
import Shuffle from '~icons/lucide/shuffle'
import SkipForward from '~icons/lucide/skip-forward'
import SlidersHorizontal from '~icons/lucide/sliders-horizontal'
import Smartphone from '~icons/lucide/smartphone'
import Sparkles from '~icons/lucide/sparkles'
import Sun from '~icons/lucide/sun'
import Table from '~icons/lucide/table'
import Trash from '~icons/lucide/trash'
import TriangleAlert from '~icons/lucide/triangle-alert'
import University from '~icons/lucide/university'
import UserPlus from '~icons/lucide/user-plus'
import UserRoundPlus from '~icons/lucide/user-round-plus'
import UserSearch from '~icons/lucide/user-search'
import Users from '~icons/lucide/users'
import X from '~icons/lucide/x'

export type IconComponent = ForwardRefExoticComponent<SVGProps<SVGSVGElement> & { title?: string }>

export const iconRegistry: Record<string, IconComponent> = {
  'activity': Activity,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'book-open': BookOpen,
  'book-open-check': BookOpenCheck,
  'bot': Bot,
  'check': Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle-check': CircleCheck,
  'circuit-board': CircuitBoard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'cloud-upload': CloudUpload,
  'construction': Construction,
  'copy': Copy,
  'cpu': Cpu,
  'dices': Dices,
  'ellipsis': Ellipsis,
  'eye': Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  'fingerprint': FingerprintPattern,
  'flask-conical': FlaskConical,
  'graduation-cap': GraduationCap,
  'hard-drive': HardDrive,
  'help-circle': CircleQuestionMark,
  'id-card': IdCard,
  'info': Info,
  'key-round': KeyRound,
  'laptop': Laptop,
  'layout-dashboard': LayoutDashboard,
  'library': Library,
  'list-checks': ListChecks,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'message-circle-question': MessageCircleQuestionMark,
  'minus': Minus,
  'monitor-play': MonitorPlay,
  'monitor-smartphone': MonitorSmartphone,
  'moon': Moon,
  'notebook-text': NotebookText,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  'pen': Pen,
  'pen-line': PenLine,
  'pencil': Pencil,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'rocket': Rocket,
  'scan-search': ScanSearch,
  'school': School,
  'scroll-text': ScrollText,
  'search': Search,
  'search-x': SearchX,
  'settings-2': Settings2,
  'shield-check': ShieldCheck,
  'shuffle': Shuffle,
  'skip-forward': SkipForward,
  'sliders-horizontal': SlidersHorizontal,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'sun': Sun,
  'table': Table,
  'trash-2': Trash,
  'triangle-alert': TriangleAlert,
  'university': University,
  'user-plus': UserPlus,
  'user-round-plus': UserRoundPlus,
  'user-search': UserSearch,
  'users': Users,
  'x': X,
}
