import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = path.join(root, 'src')
const outFile = path.join(srcDir, 'components', 'ui', 'icon-registry.ts')

const collection = JSON.parse(
  fs.readFileSync(path.join(root, 'node_modules', '@iconify-json', 'lucide', 'icons.json'), 'utf8'),
)

const resolveParent = (name) => {
  const seen = new Set()
  let current = name
  while (!collection.icons[current]) {
    if (seen.has(current)) return null
    seen.add(current)
    const alias = collection.aliases?.[current]
    if (!alias) return null
    current = alias.parent
  }
  return current
}

const used = new Set()
const matches = (file) => {
  const content = fs.readFileSync(file, 'utf8')
  const re = /lucide:([a-z0-9-]+)/g
  let match
  while ((match = re.exec(content))) used.add(match[1])
}
const walk = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full)
    else if (/\.(ts|tsx)$/.test(entry.name) && full !== outFile) matches(full)
  }
}
walk(srcDir)

const toIdentifier = (specifier) =>
  specifier
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

const specifiers = new Map()
const missing = []
const entries = []
for (const name of [...used].sort()) {
  const parent = resolveParent(name)
  if (!parent) {
    missing.push(name)
    continue
  }
  let identifier = specifiers.get(parent)
  if (!identifier) {
    identifier = toIdentifier(parent)
    let unique = identifier
    let i = 2
    while ([...specifiers.values()].includes(unique)) unique = `${identifier}${i++}`
    identifier = unique
    specifiers.set(parent, identifier)
  }
  entries.push([name, identifier])
}

const imports = [...specifiers.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([specifier, identifier]) => `import ${identifier} from '~icons/lucide/${specifier}'`)
  .join('\n')

const map = entries
  .map(([name, identifier]) => `  '${name}': ${identifier},`)
  .join('\n')

const output = `// AUTO-GENERATED by scripts/gen-icons.mjs — run \`npm run gen:icons\` after adding icons.
import type { ForwardRefExoticComponent, SVGProps } from 'react'

${imports}

export type IconComponent = ForwardRefExoticComponent<SVGProps<SVGSVGElement> & { title?: string }>

export const iconRegistry: Record<string, IconComponent> = {
${map}
}
`

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, output)

if (missing.length) {
  console.warn(`[gen-icons] unknown icons skipped: ${missing.join(', ')}`)
}
console.log(`[gen-icons] ${entries.length} icons -> ${path.relative(root, outFile)}`)
